# This task should be run on the root user

- name: Add Tailscale signing key
  get_url:
    url: https://pkgs.tailscale.com/stable/debian/bookworm.noarmor.gpg
    dest: /usr/share/keyrings/tailscale-archive-keyring.gpg
    mode: "0644"

- name: Add Tailscale repository
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/tailscale-archive-keyring.gpg] https://pkgs.tailscale.com/stable/debian bookworm main
    codename: bookworm

    state: present

- name: Update and upgrade APT packages
  apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: full

- name: Install APT packages
  apt:
    state: latest

    pkg:
      - ufw
      - sudo
      - tailscale

      - ansible
      #- just
