
    - name: Disable lid suspend trigger
      become: true

      copy:
        src: ./logind.conf
        dest: /etc/systemd/logind.conf
        owner: root
        group: root
        mode: '0644'

    - name: Apply hardened OpenSSH server configuration
      become: true

      copy:
        src: ./sshd_config
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: '0644'