- name: "Remove previous Docker versions"
  become: true

  apt:
    state: absent

    pkg:
      - docker.io
      - docker-doc
      - docker-compose
      - podman-docker
      - containerd
      - runc

- name: Install APT Docker dependencies
  become: true

  apt:
    state: latest

    pkg:
      - ca-certificates
      - curl
      - gpg
      - python3-docker

- name: Add Docker GPG APT Key
  become: true

  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker APT repository
  become: true

  apt_repository:
    repo: deb https://download.docker.com/linux/debian bookworm stable
    state: present

- name: Install docker-ce
  become: true

  apt:
    name: docker-ce
    state: latest

- name: Init a new Docker Swarm
  become: true

  community.docker.docker_swarm:
    state: present

- name: Setting up shared Docker network
  become: true

  community.docker.docker_network:
    name: shared
    attachable: true
    driver: overlay
    scope: swarm
