# Avoid leaving unwanted ports open by accident
- name: Set UFW to default values
  become: true
  community.general.ufw:
    state: reset

- name: Deny everything on UFW
  become: true
  community.general.ufw:
    policy: deny
    logging: "on"

- name: Allow safe TCP ports with UFW
  become: true
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - "80"
    - "443"
    - "25565"

- name: "Limit SSH to only specific IP ranges with UFW"
  become: true
  community.general.ufw:
    rule: limit
    port: ssh
    proto: tcp
    from: "{{ item }}"
  loop:
    - 192.168.0.0/16
    - 100.64.0.0/10

- name: Reload and enable UFW on boot
  become: true
  community.general.ufw:
    state: enabled
