- name: Setup the server
  hosts: user

  tasks:
    - name: Setup UFW
      include_tasks: tasks/ufw.yml

    - name: Setup Docker
      include_tasks: tasks/docker.yml

    - name: Clone homelab Git repository
      git:
        repo: https://github.com/kutu-dev/homelab.git
        dest: /home/homelab/repository
        update: false

    - name: Setup misc config files
      include_tasks: tasks/config.yml

    - name: Make required data directories
      file:
        path: "/home/homelab/data/{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - minecraft
