- name: Set the Docker Swarm secrets
  hosts: user

  tasks:
    - name: Change the secret data from the Ansible Vault
      become: true

      community.docker.docker_secret:
        name: "{{ item }}"
        data: "{{ vars[item] }}"
        state: present
      loop:
        - traefik_porkbun_api_key
        - traefik_porkbun_secret_api_key
        - seafile_maria_db_root_password
